# -*- coding: utf-8 -*-
"""order.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L0waKq778w9mwAiwEkhn-HSDYuFvsqdX
"""

def main():
    while True:
        print("\n" + "╔" + "═"*32 + "╗")
        print("║   歡迎使用珍饕餐廳點餐管理系統   ║")
        print("╚" + "═"*32 + "╝")
        print("  1.  ✨ 顧客新點餐開單 (New Order)")
        print("  2.  📊 檢視後台營運報表 (Show Statistics)")
        print("  3.  🗑️  撤銷上一筆錯誤訂單 (Delete Last Order) ※店長權限")
        print("  0.  🚪 關閉並安全退出系統 (Exit)")
        print("-" * 36)

        choice = input(">> 請輸入功能對應數字 (0-3): ").strip()

        if choice == "1":
            current_order = create_order()
            if len(current_order) > 0:
                if checkout(current_order):
                    save_order(current_order)
                    print("✅【系統通知】該筆點餐訂單已成功存檔至後台歷史資料庫。")
            else:
                print("↩️【回主選單】您剛剛未選購任何餐點，已自動取消本次開單。")

        elif choice == "2":
            show_statistics()
        elif choice == "3":
            delete_last_order()
        elif choice == "0":
            print("👋【感謝使用】系統已安全登出並關閉。祝您今日營業額長紅！")
            break
        else:
            print("❌【選項錯誤】無此功能代碼，請重新輸入 0 到 3 之間的整數。")

if __name__ == "__main__":
    main()